version: '3'
services:
  microservicio:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: microdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin666
